// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1tZLkQIOzXX-4yVFtcgunGGsdy9XW8Vo',
    appId: '1:394398246893:web:efb87810477dc73df9a9e4',
    messagingSenderId: '394398246893',
    projectId: 'artisan-18c0c',
    authDomain: 'artisan-18c0c.firebaseapp.com',
    storageBucket: 'artisan-18c0c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3vEcKekbR7-tI-YnSceu6QIrAS7U6QMo',
    appId: '1:394398246893:android:27fe43c133020d59f9a9e4',
    messagingSenderId: '394398246893',
    projectId: 'artisan-18c0c',
    storageBucket: 'artisan-18c0c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1tZLkQIOzXX-4yVFtcgunGGsdy9XW8Vo',
    appId: '1:394398246893:web:771d70eb84907f29f9a9e4',
    messagingSenderId: '394398246893',
    projectId: 'artisan-18c0c',
    authDomain: 'artisan-18c0c.firebaseapp.com',
    storageBucket: 'artisan-18c0c.firebasestorage.app',
  );
}
